version: "3"

services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:3000"
    environment:
      DB_HOST: postgres
      DB_NAME: edgecomputing
      DB_USER: edgecomputing
      DB_PASS: edgecomputing

  worker:
    build: ./raytracer
    depends_on:
      - app
    ports:
      - "9000:9000"
    volumes:
      - "./edge-computing:/edge-computing"

  client:
    build: ./client
    depends_on:
      - app
    ports:
      - "3000:80"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: bitnami/postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/bitnami
    environment:
      POSTGRESQL_USERNAME: edgecomputing
      POSTGRESQL_PASSWORD: edgecomputing
      POSTGRESQL_DATABASE: edgecomputing

volumes:
  redis-data:
  postgres-data:
