version: "3"

services:
  app:
    build: .
    depends_on:
      # - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
    restart: always
    # environment:
    #   DB_HOST: postgres
    #   DB_NAME: edgecomputing
    #   DB_USER: edgecomputing
    #   DB_PASS: edgecomputing
    expose:
      - 3000

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # postgres:
  #   image: bitnami/postgresql
  #   restart: always
  #   volumes:
  #     - postgres-data:/bitnami
  #   environment:
  #     POSTGRESQL_USERNAME: edgecomputing
  #     POSTGRESQL_PASSWORD: edgecomputing
  #     POSTGRESQL_DATABASE: edgecomputing

volumes:
  redis-data:
  # postgres-data:
