version: "3"

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: postgres
      DB_NAME: edgecomputing
      DB_USER: edgecomputing
      DB_PASS: edgecomputing

  postgres:
    image: bitnami/postgresql
    restart: always
    volumes:
      - postgres-data:/bitnami
    environment:
      POSTGRESQL_USERNAME: edgecomputing
      POSTGRESQL_PASSWORD: edgecomputing
      POSTGRESQL_DATABASE: edgecomputing

volumes:
  postgres-data:
